
[general]
	#Aptitudes Max Level [default: 32]
	#Range: 2 ~ 1000
	aptitudeMaxLevel = 64
	#First aptitudes level cost: [default: 5]
	#Range: 1 ~ 1000
	aptitudeFirstCostLevel = 1
	#Show potions overlay over skills [default: true]
	showPotionsHud = true
	#Lock item list: (see the wiki if you wanna know how to add a unlock item)
	lockItemList = ["minecraft:anvil#building:10", "minecraft:chipped_anvil#building:10", "minecraft:damaged_anvil#building:10", "minecraft:brewing_stand#building:12;magic:12;intelligence:10", "minecraft:enchanting_table#magic:10", "minecraft:beacon#building:18", "minecraft:end_crystal#magic:30;building:22", "minecraft:ender_chest#magic:18", "minecraft:respawn_anchor#magic:18", "minecraft:shulker_box#magic:18", "minecraft:white_shulker_box#magic:18", "minecraft:light_gray_shulker_box#magic:18", "minecraft:gray_shulker_box#magic:18", "minecraft:black_shulker_box#magic:18", "minecraft:brown_shulker_box#magic:18", "minecraft:red_shulker_box#magic:18", "minecraft:orange_shulker_box#magic:18", "minecraft:yellow_shulker_box#magic:18", "minecraft:lime_shulker_box#magic:18", "minecraft:green_shulker_box#magic:18", "minecraft:cyan_shulker_box#magic:18", "minecraft:light_blue_shulker_box#magic:18", "minecraft:blue_shulker_box#magic:18", "minecraft:purple_shulker_box#magic:18", "minecraft:magenta_shulker_box#magic:18", "minecraft:pink_shulker_box#magic:18", "minecraft:dragon_egg#magic:27", "minecraft:wither_skeleton_skull#magic:8;building:6", "minecraft:lodestone#building:16;intelligence:6", "minecraft:smithing_table#building:20;intelligence:13", "minecraft:grindstone#building:16;intelligence:13", "minecraft:cartography_table#building:12;intelligence:10", "minecraft:stonecutter#building:6;strength:4", "minecraft:smoker#building:4", "minecraft:blast_furnace#building:4", "minecraft:loom#building:8;intelligence:6", "minecraft:name_tag#intelligence:8", "minecraft:fishing_rod#luck:2", "minecraft:bone_meal#luck:10", "minecraft:shears#building:2", "minecraft:lead#intelligence:2", "minecraft:spyglass#intelligence:4;dexterity:2", "minecraft:brush#intelligence:10", "minecraft:fire_charge#intelligence:2", "minecraft:flint_and_steel#intelligence:4", "minecraft:redstone#intelligence:2", "minecraft:redstone_torch#intelligence:2", "minecraft:repeater#intelligence:2", "minecraft:comparator#intelligence:2", "minecraft:writable_book#intelligence:4", "minecraft:written_book#intelligence:4", "minecraft:tnt#intelligence:10", "minecraft:lectern#intelligence:6;building:2", "minecraft:ender_pearl#magic:6", "minecraft:ender_eye#magic:13", "minecraft:bow#dexterity:4;strength:2", "minecraft:crossbow#dexterity:6;strength:2", "minecraft:saddle#dexterity:4", "minecraft:elytra#dexterity:27", "minecraft:firework_rocket#dexterity:20;intelligence:18", "minecraft:experience_bottle#magic:12;luck:8", "minecraft:wheat_seeds#intelligence:4", "minecraft:cocoa_beans#intelligence:4", "minecraft:pumpkin_seeds#intelligence:4", "minecraft:melon_seeds#intelligence:4", "minecraft:beetroot_seeds#intelligence:4", "minecraft:torchflower_seeds#intelligence:4", "minecraft:pitcher_pod#intelligence:4", "minecraft:glow_berries#intelligence:4", "minecraft:sweet_berries#intelligence:4", "minecraft:nether_wart:#intelligence:10;magic:6", "minecraft:egg#constitution:2", "minecraft:frogspawn#intelligence:12;constitution:13", "minecraft:turtle_egg#intelligence:12;constitution:13", "minecraft:sniffer_egg#intelligence:12;constitution:13", "minecraft:oak_sapling#intelligence:6", "minecraft:spruce_sapling#intelligence:6", "minecraft:birch_sapling#intelligence:6", "minecraft:jungle_sapling#intelligence:6", "minecraft:acacia_sapling#intelligence:6", "minecraft:dark_oak_sapling#intelligence:6", "minecraft:mangrove_propagule#intelligence:6", "minecraft:cherry_sapling#intelligence:6", "minecraft:azalea#intelligence:6", "minecraft:flowering_azalea#intelligence:6", "minecraft:brown_mushroom#intelligence:6", "minecraft:red_mushroom#intelligence:6", "minecraft:crimson_fungus#intelligence:6", "minecraft:warped_fungus#intelligence:6", "minecraft:bamboo#intelligence:6", "minecraft:sugar_cane#intelligence:6", "minecraft:cactus#intelligence:6", "minecraft:chorus_plant#intelligence:10", "minecraft:chorus_flower#intelligence:10", "minecraft:shield#defense:4;constitution:2", "minecraft:chainmail_helmet#defense:2", "minecraft:chainmail_chestplate#defense:2", "minecraft:chainmail_leggings#defense:2", "minecraft:chainmail_boots#defense:2", "minecraft:iron_helmet#defense:6", "minecraft:iron_chestplate#defense:6", "minecraft:iron_leggings#defense:6", "minecraft:iron_boots#defense:6", "minecraft:golden_helmet#defense:6;magic:4", "minecraft:golden_chestplate#defense:6;magic:4", "minecraft:golden_leggings#defense:6;magic:4", "minecraft:golden_boots#defense:6;magic:4", "minecraft:diamond_helmet#defense:13", "minecraft:diamond_chestplate#defense:13", "minecraft:diamond_leggings#defense:13", "minecraft:diamond_boots#defense:13", "minecraft:netherite_helmet#defense:22", "minecraft:netherite_chestplate#defense:22", "minecraft:netherite_leggings#defense:22", "minecraft:netherite_boots#defense:22", "minecraft:turtle_helmet#defense:6;dexterity:4", "minecraft:golden_horse_armor#defense:4;dexterity:2", "minecraft:iron_horse_armor#defense:6;dexterity:4", "minecraft:diamond_horse_armor#defense:12;dexterity:10", "minecraft:totem_of_undying#constitution:16;magic:12<droppable>", "minecraft:trident#strength:20;dexterity:16", "minecraft:iron_hoe#building:6", "minecraft:iron_shovel#building:6", "minecraft:iron_pickaxe#building:6", "minecraft:iron_axe#strength:8;building:6", "minecraft:iron_sword#strength:6", "minecraft:golden_hoe#building:4", "minecraft:golden_shovel#building:4", "minecraft:golden_pickaxe#building:4", "minecraft:golden_axe#building:6;strength:4", "minecraft:golden_sword#strength:4", "minecraft:diamond_hoe#building:13", "minecraft:diamond_shovel#building:13", "minecraft:diamond_pickaxe#building:13", "minecraft:diamond_axe#strength:16;building:13", "minecraft:diamond_sword#strength:13", "minecraft:netherite_hoe#building:22", "minecraft:netherite_shovel#building:22", "minecraft:netherite_pickaxe#building:22", "minecraft:netherite_axe#strength:24;building:22", "minecraft:netherite_sword#strength:22", "minecraft:honey_bottle#constitution:2", "minecraft:potion#luck:2", "minecraft:splash_potion#luck:6;dexterity:4", "minecraft:lingering_potion#luck:6;magic:4"]

[passives]
	#Attack Damage passive value at max level [default: 1.5]
	#Range: 0.0 ~ 10000.0
	attackDamageValue = 1.9
	#Attack Knockback passive value at max level [default: 0.4]
	#Range: 0.0 ~ 10000.0
	attackKnockbackValue = 0.6
	#Max Health passive value at max level [default: 20.0]
	#Range: 0.0 ~ 10000.0
	maxHealthValue = 40.0
	#Knockback Resistance passive value at max level [default: 0.5]
	#Range: 0.0 ~ 10000.0
	knockbackResistanceValue = 0.7
	#Movement Speed passive value at max level [default: 0.05]
	#Range: 0.0 ~ 10000.0
	movementSpeedValue = 0.07
	#Projectile Damage passive value at max level [default: 5.0]
	#Range: 0.0 ~ 10000.0
	projectileDamageValue = 7.0
	#Armor passive value at max level [default: 4.0]
	#Range: 0.0 ~ 10000.0
	armorValue = 6.0
	#Armor Toughness passive value at max level [default: 1.0]
	#Range: 0.0 ~ 10000.0
	armorToughnessValue = 3.0
	#Attack Speed passive value at max level [default: 0.4]
	#Range: 0.0 ~ 10000.0
	attackSpeedValue = 0.8
	#Entity Reach passive value at max level [default: 1.0]
	#Range: 0.0 ~ 10000.0
	entityReachValue = 1.6
	#Block Reach passive value at max level [default: 1.5]
	#Range: 0.0 ~ 10000.0
	blockReachValue = 2.0
	#Break Speed passive value at max level [default: 0.5]
	#Range: 0.0 ~ 10000.0
	breakSpeedValue = 1.0
	#Beneficial Effect passive value at max level [default: 60.0]
	#Range: 0.0 ~ 10000.0
	beneficialEffectValue = 90.0
	#Magic Resist passive value at max level [default: 0.5]
	#Range: 0.0 ~ 10000.0
	magicResistValue = 1.0
	#Critical Damage passive value at max level [default: 0.25]
	#Range: 0.0 ~ 10000.0
	criticalDamageValue = 0.75
	#Luck passive value at max level [default: 2.0]
	#Range: 0.0 ~ 10000.0
	luckValue = 5.0

[skills]
	#One Handed skill damage amplifier increase [default: 0.5]
	#Range: 0.0 ~ 10000.0
	oneHandedAmplifier = 0.5
	#Fighting Spirit skill strength potion effect boost [default: 1]
	#Range: 1 ~ 255
	fightingSpiritBoost = 1.5
	#Fighting Spirit skill strength potion effect duration [default: 3]
	#Range: 1 ~ 3600
	fightingSpiritDuration = 3
	#Berserker skill health percent [default: 30]
	#Range: 0 ~ 100
	berserkerPercent = 30
	#Athletics skill air modifier multiply [default: 1.5]
	#Range: 0.0 ~ 500.0
	athleticsModifier = 1.5
	#Lion Heart skill negative potion effect percent [default: 50]
	#Range: 0 ~ 100
	lionHeartPercent = 50
	#Quick Reposition skill speed potion effect boost [default: 2]
	#Range: 1 ~ 255
	quickRepositionBoost = 2
	#Quick Reposition skill speed potion effect duration [default: 3]
	#Range: 1 ~ 3600
	quickRepositionDuration = 3
	#Stealth Mastery skill enemy vision percent [default: 20]
	#Range: 0 ~ 100
	stealthMasteryUnSneakPercent = 20
	#Stealth Mastery skill enemy vision percent when player is sneaking [default: 60]
	#Range: 0 ~ 100
	stealthMasterySneakPercent = 60
	#Stealth Mastery skill arrow damage modifier multiply [default: 1.25]
	#Range: 0.0 ~ 100.0
	stealthMasteryModifier = 1.25
	#Counter Attack skill duration to return the attack [default: 3]
	#Range: 0 ~ 3600
	counterAttackDuration = 3
	#Counter Attack skill damage returned percent [default: 50]
	#Range: 0 ~ 500
	counterAttackPercent = 50
	#Diamond Skin defence potion effect boost [default: 2]
	#Range: 1 ~ 255
	diamondSkinBoost = 2
	#Diamond skill defense amplifier increase when player is sneaking [default: 2.0]
	#Range: 0.0 ~ 10000.0
	diamondSkinSneakAmplifier = 2.0
	#Haggler skill villager trades cost percent reduced [default: 20]
	#Range: 0 ~ 100
	hagglerPercent = 20
	#Expert Alchemist skill potion amplifier increase [default: 1.0]
	#Range: 0.0 ~ 10000.0
	alchemyManipulationAmplifier = 1.0
	#Obsidian Smasher skill obsidian breaking speed modifier multiply [default: 10.0]
	#Range: 0.0 ~ 100.0
	obsidianSmasherModifier = 10.0
	#Treasure Hunter skill probability chance to get a treasure in dirt, example: 1/500 it means that 1 out of every 500 (0,2%) dirt blocks you can get a treasure. [default: 500]
	#Range: 1 ~ 10000
	treasureHunterProbability = 500
	#Treasure Hunter skill treasures item list: (see the wiki if you wanna know how to add a treasure item)
	treasureHunterItemList = ["minecraft:flint", "minecraft:clay_ball", "trashList[minecraft:feather;minecraft:bone_meal]", "lostToolList[minecraft:stick;minecraft:wooden_pickaxe{Damage:59};minecraft:wooden_shovel{Damage:59};minecraft:wooden_axe{Damage:59}]", "discList[minecraft:music_disc_13;minecraft:music_disc_cat;minecraft:music_disc_blocks;minecraft:music_disc_chirp;minecraft:music_disc_far;minecraft:music_disc_mall;minecraft:music_disc_mellohi;minecraft:music_disc_stal;minecraft:music_disc_strad;minecraft:music_disc_ward;minecraft:music_disc_11;minecraft:music_disc_wait]", "seedList[minecraft:beetroot_seeds;minecraft:wheat_seeds;minecraft:pumpkin_seeds;minecraft:melon_seeds;minecraft:brown_mushroom;minecraft:red_mushroom]", "mineralList[minecraft:raw_iron;minecraft:raw_gold;minecraft:raw_copper;minecraft:coal;minecraft:charcoal]"]
	#Convergence skill probability chance to obtain part of the spent material, example: 1/8 it means that 1 out of every 8 (12,5%) crafted items you can obtain a part of the spent material. [default: 8]
	#Range: 1 ~ 10000
	convergenceProbability = 8
	#Convergence skill convergence item list: (see the wiki if you wanna know how to add a convergence item)
	convergenceItemList = ["minecraft:iron_sword#minecraft:iron_ingot", "minecraft:iron_pickaxe#minecraft:iron_ingot", "minecraft:iron_axe#minecraft:iron_ingot", "minecraft:iron_shovel#minecraft:iron_nugget", "minecraft:iron_hoe#minecraft:iron_ingot", "minecraft:golden_sword#minecraft:gold_ingot", "minecraft:golden_pickaxe#minecraft:gold_ingot", "minecraft:golden_axe#minecraft:gold_ingot", "minecraft:golden_shovel#minecraft:gold_ingot", "minecraft:golden_hoe#minecraft:gold_ingot", "minecraft:diamond_sword#minecraft:diamond", "minecraft:diamond_pickaxe#minecraft:diamond", "minecraft:diamond_axe#minecraft:diamond", "minecraft:chainmail_helmet#minecraft:iron_nugget", "minecraft:chainmail_chestplate#minecraft:iron_nugget", "minecraft:chainmail_leggings#minecraft:iron_nugget", "minecraft:chainmail_boots#minecraft:iron_nugget", "minecraft:iron_helmet#minecraft:iron_ingot", "minecraft:iron_chestplate#minecraft:iron_ingot", "minecraft:iron_leggings#minecraft:iron_ingot", "minecraft:iron_boots#minecraft:iron_ingot", "minecraft:golden_helmet#minecraft:gold_ingot", "minecraft:golden_chestplate#minecraft:gold_ingot", "minecraft:golden_leggings#minecraft:gold_ingot", "minecraft:golden_boots#minecraft:gold_ingot", "minecraft:diamond_helmet#minecraft:diamond", "minecraft:diamond_chestplate#minecraft:diamond", "minecraft:diamond_leggings#minecraft:diamond", "minecraft:diamond_boots#minecraft:diamond", "minecraft:netherite_upgrade_smithing_template#minecraft:diamond", "minecraft:sentry_armor_trim_smithing_template#minecraft:diamond", "minecraft:vex_armor_trim_smithing_template#minecraft:diamond", "minecraft:wild_armor_trim_smithing_template#minecraft:diamond", "minecraft:coast_armor_trim_smithing_template#minecraft:diamond", "minecraft:dune_armor_trim_smithing_template#minecraft:diamond", "minecraft:wayfinder_armor_trim_smithing_template#minecraft:diamond", "minecraft:raiser_armor_trim_smithing_template#minecraft:diamond", "minecraft:shaper_armor_trim_smithing_template#minecraft:diamond", "minecraft:host_armor_trim_smithing_template#minecraft:diamond", "minecraft:ward_armor_trim_smithing_template#minecraft:diamond", "minecraft:silence_armor_trim_smithing_template#minecraft:diamond", "minecraft:tide_armor_trim_smithing_template#minecraft:diamond", "minecraft:snout_armor_trim_smithing_template#minecraft:diamond", "minecraft:rib_armor_trim_smithing_template#minecraft:diamond", "minecraft:eye_armor_trim_smithing_template#minecraft:diamond", "minecraft:spire_armor_trim_smithing_template#minecraft:diamond"]
	#Life Eater skill life steal amplifier increase [default: 1.0]
	#Range: 0.0 ~ 10000.0
	lifeEaterModifier = 1.0
	#Critical Roll skill critic modifier multiply when you roll a 6 [default: 1.25]
	#Range: 0.0 ~ 100.0
	criticalRoll6Modifier = 1.25
	#Critical Roll skill critic probability reduce when you roll a 1, example: 1/3 it means that 1 out of every 3 (33%) the critic damage will be reduced. [default: 3]
	#Range: 1 ~ 10000
	criticalRoll1Probability = 3
	#Lucky Drop skill mob drops modifier multiply [default: 2.0]
	#Range: 0.0 ~ 10000.0
	luckyDropModifier = 2.0
	#Lucky Drop skill mobs drops probability, example: 1/5 it means that 1 out of every 5 (20%) the mob drops will be multiplied. [default: 10]
	#Range: 1 ~ 10000
	luckyDropProbability = 10
	#Limit Breaker skill deal damage amplifier [default: 999.0]
	#Range: 0.0 ~ 10000.0
	limitBreakerAmplifier = 999.0
	#Limit Breaker skill deal damage probability, example: 1/100 it means that 1 in 100 (1%) to deal damage amplified. [default: 100]
	#Range: 1 ~ 10000
	limitBreakerProbability = 100

